sudo: required
language: go
services:
  - docker
go:
  - 1.x
script:
  - go fmt $(go list ./... | grep -v vendor) | wc -l | grep 0
  - make test
after_success:
  - if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      make container;
      docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}" quay.io;
      docker push quay.io/k8scsi/driver-registrar:v0.2.0;
    fi
